version: '3'
services:
  devops:
    image: vamshi9133/bus1repotransport:latest
    ports:
      - "50:80"
    deploy:
      replicas: 3

  aws:
    image: vamshi9133/jeep1repotransport:latest
    ports:
      - "51:80"
    deploy:
      replicas: 3

  datascience:
    image: vamshi9133/car1repotransport:latest
    ports:
      - "52:80"
    deploy:
      replicas: 3

  azure:
    image: vamshi9133/bike1repotransport:latest
    ports:
      - "53:80"
    deploy:
      replicas: 3
